openapi: '3.0.2'
info:
  title: API сервера ThunderBoard
  version: '1.0'

tags:
  - name: Аутентификация
    description: Методы аутентификации
  - name: Учётные записи
    description: Методы взаимодействия с учётными записями
  - name: Проекты
    description: Методы взаимодействия с проектами
  - name: Задачи
    description: Методы взаимодействия с задачами

paths:
  /log-in:
    $ref: paths/authentication/log_in.yml
  /log-out:
    $ref: paths/authentication/log_out.yml

  /users:
    $ref: paths/users/get.yml
  /user:
    $ref: paths/users/get_user.yml
  /users/add:
    $ref: paths/users/add.yml
  /users/remove:
    $ref: paths/users/remove.yml

  /projects:
    $ref: paths/projects/get.yml
  /project:
    $ref: paths/projects/get_project.yml
  /projects/add:
    $ref: paths/projects/add.yml
  /projects/change:
    $ref: paths/projects/change.yml
  /projects/add-user:
    $ref: paths/projects/add_user.yml
  /projects/remove-user:
    $ref: paths/projects/remove_user.yml

  /tasks:
    $ref: paths/tasks/get.yml
  /task:
    $ref: paths/tasks/get_task.yml
  /tasks/add:
    $ref: paths/tasks/add.yml
  /tasks/change:
    $ref: paths/tasks/change.yml

components:
  securitySchemes:
    $ref: security/jwt.yml
