openapi: '3.0.2'
info:
  title: API сервера ThunderBoard
  version: '1.0'

tags:
  - name: Аутентификация
    description: Методы аутентификации
  - name: Учётные записи
    description: Методы взаимодействия с учётными записями
  - name: Проекты
    description: Методы взаимодействия с проектами
  - name: Задачи
    description: Методы взаимодействия с задачами

paths:
  /log-in:
    post:
      $ref: paths/authentication/log_in.yml
  /log-out:
    get:
      $ref: paths/authentication/log_out.yml

  /users:
    get:
      $ref: paths/users/get.yml
  /user/{userId}:
    get:
      $ref: paths/user/get.yml
    post:
      $ref: paths/user/post.yml
    delete:
      $ref: paths/user/delete.yml

  /projects:
    get:
      $ref: paths/projects/get.yml
  /project/{projectId}:
    get:
      $ref: paths/project/get.yml
    post:
      $ref: paths/project/post.yml
    patch:
      $ref: paths/project/patch.yml
  /project/{projectId}/user/{userId}:
    put:
      $ref: paths/project/user/put.yml
    delete:
      $ref: paths/project/user/delete.yml

  /tasks:
    $ref: paths/tasks/get.yml
  /task:
    $ref: paths/tasks/get_task.yml
  /tasks/add:
    $ref: paths/tasks/add.yml
  /tasks/change:
    $ref: paths/tasks/change.yml

components:
  securitySchemes:
    $ref: security/jwt.yml
