post:
  summary: Добавить задачу
  description: |
    Добавить задачу в проект

    *Доступна менеджерам проекта*

  tags:
    - Задачи
  security:
    - bearerAuth: []
  requestBody:
    content:
      application/json:
        schema:
          type: object
          description: Задача
          required:
            - project
            - name
            - description
            - userEmail
            - proposedTime
            - remainingTime
          properties:
            project:
              description: Имя проекта
              type: string
              example: Первый проект
            name:
              description: Имя задачи
              type: string
              example: Создание новых задач
            description:
              description: Описание задачи
              type: string
              example: Создавать задачи в проекте
            userEmail:
              description: Адрес электронной почты пользователя
              type: string
              format: email
              example: ivanov.ii@org.org
            proposedTime:
              description: Выделенное время
              type: integer
              format: int64
              example: 10
            remainingTime:
              description: Потраченное время
              type: integer
              format: int64
              example: 0
  responses:
    '200':
      description: OK
    '400':
      description: Ошибка
      content:
        application/json:
          schema:
            $ref: "../common/error.yml"
    '401':
      description: Ошибка аутентификации
