post:
  summary: Изменить задачу
  description: |
    Изменить задачу

    *Доступна менеджерам и ограниченно участникам проекта*

  tags:
    - Задачи
  security:
    - bearerAuth: []
  requestBody:
    content:
      application/json:
        schema:
          type: object
          description: Задача
          required:
            - project
            - name
          properties:
            project:
              description: Имя проекта
              type: string
              example: Первый проект
            name:
              description: Имя задачи
              type: string
              example: Создание новых задач
            newName:
              description: Новое имя задачи (только для менеджеров)
              type: string
              example: Создание новых задач 1
            description:
              description: Описание задачи (только для менеджеров)
              type: string
              example: Создавать задачи в проекте
            userEmail:
              description: Адрес электронной почты пользователя
              type: string
              format: email
              example: ivanov.ii@org.org
            status:
              type: string
              description: Статус задачи
              example: Разрешено
            proposedTime:
              description: Выделенное время (только для менеджеров)
              type: integer
              format: int64
              example: 10
            remainingTime:
              description: Потраченное время
              type: integer
              format: int64
              example: 0
  responses:
    '200':
      description: OK
    '400':
      description: Ошибка
      content:
        application/json:
          schema:
            $ref: "../common/error.yml"
    '401':
      description: Ошибка аутентификации
