get:
  summary: Получить задачи проекта
  description: |
    Получить задачи проекта

    *Доступна всем авторизованным пользователям*

  tags:
    - Задачи
  security:
    - bearerAuth: []
  parameters:
    - name: notFinal
      description: Не получать завершённые задачи
      in: query
      required: false
      schema:
        type: boolean
    - name: project
      description: Имя проекта
      in: query
      required: true
      schema:
        type: string
    - $ref: ../common/pagination/page.yml
    - $ref: ../common/pagination/per_page.yml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              statuses:
                $ref: ../common/statuses/statuses.yml
              tasks:
                description: Распределение задач по статусам
                type: array
                items:
                  $ref: ../common/task.yml
    '400':
      description: Ошибка
      content:
        application/json:
          schema:
            $ref: ../common/error.yml
    '401':
      description: Ошибка аутентификации
