get:
  summary: Получить задачи проекта
  description: |
    Получить задачи проекта

    *Доступна всем авторизованным пользователям*

  tags:
    - Задачи
  security:
    - bearerAuth: []
  parameters:
    - name: notFinal
      description: Не получать завершённые задачи
      in: query
      required: false
      schema:
        type: boolean
    - name: project
      description: Имя проекта
      in: query
      required: true
      schema:
        type: string
    - $ref: ../common/pagination/page.yml
    - $ref: ../common/pagination/per_page.yml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              statuses:
                $ref: ../common/statuses/statuses.yml
              tasks:
                description: Распределение задач по статусам
                type: array
                items:
                  type: object
                  description: Задача
                  properties:
                    status:
                      type: string
                      description: Статус задачи
                      example: Назначено
                    name:
                      type: string
                      description: Название задачи
                      example: Создание новых задач
                    description:
                      type: string
                      description: Описание задачи
                      example: Создавать задачи в проекте
                    user:
                      type: object
                      description: Исполнитель
                      properties:
                        name:
                          description: Имя пользователя
                          type: string
                          example: Иванов Иван Иванович
                        email:
                          description: Адрес электронной почты пользователя
                          type: string
                          format: email
                          example: ivanov.ii@org.org
    '400':
      description: Ошибка
      content:
        application/json:
          schema:
            $ref: ../common/error.yml
    '401':
      description: Ошибка аутентификации
