get:
  summary: Получить задачу по проекту и имени
  description: |
    Получить задачу по проекту и имени

    *Доступна всем авторизованным пользователям*

  tags:
    - Задачи
  security:
    - bearerAuth: []
  parameters:
    - name: project
      description: Имя проекта
      in: query
      required: true
      schema:
        type: string
    - name: name
      description: Название задачи
      in: query
      required: true
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../common/task.yml
    '400':
      description: Ошибка
      content:
        application/json:
          schema:
            $ref: ../common/error.yml
    '401':
      description: Ошибка аутентификации
