type: object
description: Проект
required:
  - name
  - description
properties:
  name:
    description: Имя проекта
    type: string
    example: Первый проект
  description:
    description: Описание проекта
    type: string
    example: Проект несения добра
